FROM php:8.4-fpm

MAINTAINER Clement Yuan <spyworldxp@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        wget \
        unzip \
        libbz2-dev \
        libcurl4-openssl-dev \
        libxml2-dev \
        libldap2-dev \
        zlib1g-dev \
        libpng-dev \
        unixodbc-dev \
        firebird-dev \
        libpq-dev \
        libsqlite3-dev \
        libpspell-dev \
        libedit-dev \
        libsnmp-dev \
        libtidy-dev \
        libc-client2007e-dev \
        libkrb5-dev \
        freetds-dev \
        libenchant-2-dev \
        libgmp-dev \
        libonig-dev \
        libxslt1-dev \
        libzip-dev \
        libsodium-dev \
        libwebp-dev \
        libjpeg62-turbo-dev \
        libxpm-dev \
        libfreetype6-dev \
        libmagickwand-dev \
        libmemcached-dev \
        libmcrypt-dev \
        libargon2-dev \
        libaio1 \
    && ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h \
    && docker-php-source extract \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
    && docker-php-ext-install ldap \
    && docker-php-ext-configure pdo_odbc  --with-pdo-odbc=unixODBC,/usr/ \
    && docker-php-ext-install pdo_odbc \
    && docker-php-ext-configure pdo_dblib --with-libdir=/lib/x86_64-linux-gnu \
    && docker-php-ext-install pdo_dblib \
    && docker-php-ext-configure gd \
      --disable-gd-jis-conv --with-freetype=/usr --with-jpeg=/usr --with-webp=/usr   --with-xpm=/usr \
    && docker-php-ext-install gd \
    && docker-php-ext-install bcmath bz2 calendar ctype curl dba dl_test dom enchant exif ffi fileinfo filter ftp gettext gmp iconv mbstring mysqli opcache pcntl pdo pdo_firebird pdo_mysql pdo_pgsql pdo_sqlite pgsql  posix  session shmop simplexml snmp soap sockets sodium sysvmsg sysvsem sysvshm tidy xml xmlwriter xsl zip intl \
    && set -x \
    && cd /usr/src/php/ext/odbc \
    && phpize \
    && sed -ri 's@^ *test +"\$PHP_.*" *= *"no" *&& *PHP_.*=yes *$@#&@g' configure \
    && ./configure --with-unixODBC=shared,/usr \
    && docker-php-ext-install odbc \
    && pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=dockerhost" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.start_with_request=trigger" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.output_dir=/tmp/xdebug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && cat /usr/local/etc/php/conf.d/xdebug.ini \
    && php -i | grep xdebug.remote \
    && pecl install pcov \
    && pecl install imagick && docker-php-ext-enable imagick \
    && pecl install memcached && docker-php-ext-enable memcached \
    && pecl install redis && docker-php-ext-enable redis \
    && pecl install mongodb && docker-php-ext-enable mongodb \
    && curl -L https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.23.0/php-cs-fixer.phar -o /usr/local/bin/php-cs-fixer \
    && chmod a+x /usr/local/bin/php-cs-fixer \
    && curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/bin \
    && mkdir /.composer \
    && chmod 777 /.composer \
    && curl https://phar.phpunit.de/phpunit.phar -L > phpunit.phar && chmod +x phpunit.phar && mv phpunit.phar /usr/local/bin/phpunit \
    && apt-get autoremove -y \
    && apt-get clean all \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc /usr/share/man /usr/share/locale \
    && rm -rf /usr/src/php \
    && rm -rf /tmp/pear \
  && { \
        echo 'opcache.memory_consumption=128'; \
        echo 'opcache.interned_strings_buffer=8'; \
        echo 'opcache.max_accelerated_files=4000'; \
        echo 'opcache.revalidate_freq=2'; \
        echo 'opcache.fast_shutdown=1'; \
        echo 'opcache.enable_cli=1'; \
    } > /usr/local/etc/php/conf.d/opcache-recommended.ini

ENV PATH /root/.composer/vendor/bin:/usr/local/instantclient_21_11:$PATH

EXPOSE 9000
CMD ["php-fpm"]
